
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: sigstore/cosign-installer@main

      - name: Checkout
        uses: actions/checkout@v3

      - name: Hash readme
        run: |
          sha256sum README.md

      - name: Sign container image
        run: |
          cosign sign-blob README.md
